server:
  port: 5959
  
spring:
  datasource:
    url: jdbc:tibero:thin:@10.47.39.125:8629:DB_D_GMD
    driver-class-name: com.tmax.tibero.jdbc.TbDriver
    username: tester
    password: tester
    
    hikari:
      maximum-pool-size: 4
      
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    
#aop 사용 시 순환 참조 허용
  main:
    allow-circular-references: true

#prometheus 설정
  jmx:
    enabled: true

  application:
    name: ghspring
     

#actuator에서 확인할 정보
management:
  endpoints:
    web:
      exposure:
        include: metrics, info, health, prometheus
        
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

#JPA args를 확인하는 로그
logging.level:
  org.hibernate:
    SQL: debug
    type.descriptor.sql: trace
    
